apply from: project.getRootDir().getAbsolutePath()+"/framework/common.gradle"

android {

}

dependencies {
    implementation deps.hello.resources
    implementation deps.hello.service
    implementation deps.hello.common
    implementation deps.hello.router

    api deps.dkplayer.dkplayer
    api deps.dkplayer.dkplayer_ijk
    api deps.dkplayer.dkplayer_videocache
    api deps.exoplayer

    api deps.emoji_ios

    compileOnly deps.ffmpeg_kit
    compileOnly deps.ffmpeg_kit_exception
}

